EDOLLAR:
  Monday:
  - - 15:00
    - '21:00'
  Tuesday:
  - - 16:00
    - '21:00'
  Wednesday:
  - - 17:00
    - '21:00'
  Thursday:
  - - 18:00
    - '21:00'
  Friday:
  - - 19:00
    - '21:00'
  Saturday: []
  Sunday: []
