[project]
name = "pysystemtrader"
version = "1.47"
authors = [
  { name="Robert Carver", email="rob@systematicmoney.org" },
]
description = "Systematic futures trading in Python"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: GNU v3",
    "Operating System :: Linux",
]

[project.urls]
"Homepage" = "https://github.com/robcarver17/pysystemtrade"
"Bug Tracker" = "https://github.com/robcarver17/pysystemtrade/issues"

[tool.pytest.ini_options]
norecursedirs = "examples"
addopts = "--ignore=systems/provided/moretradingrules/temp.py"

[tool.black]
line-length = 88
target-version = ['py38']
required-version = '22.12.0'
