#YAML
#
# Raw data
#
volatility_calculation:
   func: "syscore.algos.robust_vol_calc"
   days: 35
#
# Trading rules
#
trading_rules:
  ewmac8:
     function: systems.provided.example.rules.ewmac_forecast_with_defaults_no_vol
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args: 
         Lfast: 8
         Lslow: 32
     forecast_scalar: 5.3
  ewmac16:
     function: systems.provided.example.rules.ewmac_forecast_with_defaults_no_vol
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args: 
         Lfast: 16
         Lslow: 64
     forecast_scalar: 7.5
forecast_cap: 21.0
#
# forecast combination
#
forecast_weights:
     EDOLLAR:
        ewmac8: 0.50
        ewmac16: 0.50
     US10:
        ewmac8: 0.50
        ewmac16: 0.50
     BUND:
         ewmac8: 1.0
forecast_div_multiplier: 1.1
#
# Capital correction
#
percentage_vol_target: 16.0
notional_trading_capital: 100000
base_currency: "GBP"
#
# Portfolio creation
#
instrument_weights:
     EDOLLAR: 0.40
     US10: 0.40
     BUND: 0.20
instrument_div_multiplier: 1.2
#
# estimation
forecast_weight_estimate:
     ceiling_cost_SR: 0.15
#
